### ISSUE TITLE
Testimonial: first paragraph shouldn't have margin-top

### ISSUE THREAD

**Issue by busstram** [wingscms/wings#128]
#### [Ticket #65: **Testimonial: first paragraph shouldn't have margin-top**](https://zube.io/wingsplatform/wings/tickets/65)

source: https://demo.wings.dev/articles/demo-article

![Schermafdruk 2019-06-04 07.02.46.png](https://zube.io/files/wingsplatform/b226a5ea64c205e161ad5d7e55168b4f-schermafdruk-2019-06-04-07-02-46.png)

**Comment by markjjackson** [comment]
This was already fixed by wingscms/wings#172
