### ISSUE TITLE
fundraiser confirm email landing page

### ISSUE THREAD

**Issue by maartenbusstra** [wingscms/wings#292]

**Comment by jaapstronks** [comment]
@maartenbusstra currently it's https://bij1-doneer.netlify.com/fundraisers/stuur-bij1-de-kamer-in/confirmed - the default copy (without url parameters) is an error message. Either the default copy should be different or the confirmation link should add a url parameter that makes the page display something like 'thanks for confirming your email address, now go share this fundraiser' or something

**Comment by markjjackson** [comment]
@maartenbusstra what exactly need to be done for this? The projects where it wasn't working have now been updated to the latest HB and I think that fixed the issue Jaap reported.

**Comment by maartenbusstra** [comment]
@markjjackson I'm not sure if it's enough like this. I guess it could switch to some generic thank you copy when no transaction status is reported?

cc @jaapstronks
