### ISSUE TITLE
floating image margin behaviour

### ISSUE THREAD

**Issue by markjjackson** [wingscms/wings#516]
#### [Ticket #318: **[beta] bug: ul/ol list items alongside left-floating image need indentation**](https://zube.io/wingsplatform/wings/tickets/318)

[see demo page](https://beta.demo.wings.dev/bullets)

current:

![](https://screens.wings.dev/CleanShot-2020-07-14-at-10.38.13-1594715898.png)

improved:

![](https://screens.wings.dev/CleanShot-2020-07-14-at-10.40.22-1594716027.png)

**Comment by markjjackson** [comment]
@jaapstronks There isn't a universal solution to this that doesn't have drawbacks, so I would suggest simply not doing it or having the image floating on the right. It's generally a poor design decision anyway (and rarely encountered), so I'm not going to sink time into this now.

**Comment by jaapstronks** [comment]
@markjjackson ok!
